// export const TABLE_HEAD_DATA = [
// 	'Utm_Source',
// 	'Visits',
// 	'Donations #',
// 	'Total Donations ($)',
// 	'Average donation',
// 	'Conversion rate',
// 	'Utm_medium',
// 	'Utm_campaign',
// 	'Utm_term',
// 	'Utm_content',
// ];

export const TABLE_HEAD_DATA = [
  { label: "Utm_Source", key: "utmSource" },
  { label: "Visits", key: "visitCount" },
  { label: "Donations #", key: "donationCount" },
  { label: "Total Donations (USD)", key: "totalDonationValue" },
  { label: "Average Donation (USD)", key: "averageDonationValue" },
  { label: "Donation per Visitor (USD)", key: "donationsPerClick" },
  { label: "Conversion Rate", key: "conversionRate" },
  { label: "Utm_medium", key: "utmMedium" },
  { label: "Utm_campaign", key: "utmCampaign" },
  { label: "Utm_term", key: "utmTerm" },
  { label: "Utm_content", key: "utmContent" },
];

export const initialData = [
  {
    _id: 1,
    name: "Gregory Hernandez",
    roleType: "Admin",
    email: "alice@example.com",
    status: "Active",
  },
  {
    id: 2,
    name: "Bob",
    roleType: "Financial Manager",
    email: "bob@example.com",
    status: "Pending",
  },
  {
    id: 3,
    name: "Gregory Hernandez",
    roleType: "Admin",
    email: "alice@example.com",
    status: "Active",
  },
];

export const BODY_DATA = [
  {
    _id: "a1b1c1d1",
    Campaign_Name: "Fundraisers for animals rescue in Africa",
    Campaign_Details: [
      {
        Utm_source: "Google",
        Visits: 12000000,
        Donations: 80000,
        Total_Donations: 1120000,
        Average_Donations: 3000,
        Conversion_rate: 0.0001,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
      {
        Utm_source: "Facebook",
        Visits: 1110,
        Donations: 80000,
        Total_Donations: 1520000,
        Average_Donations: 900,
        Conversion_rate: 0.0001,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
      {
        Utm_source: "Twitter",
        Visits: 1110,
        Donations: 80000,
        Total_Donations: 1520000,
        Average_Donations: 900,
        Conversion_rate: 0.0001,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
      {
        Utm_source: "Instagram",
        Visits: 1110,
        Donations: 66000,
        Total_Donations: 154400,
        Average_Donations: 10000,
        Conversion_rate: 0.0001,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
      {
        Utm_source: "Snapchat",
        Visits: 1110,
        Donations: 66000,
        Total_Donations: 154400,
        Average_Donations: 10000,
        Conversion_rate: 0.0001,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
    ],
  },
  {
    _id: "a1b1casdjn",
    Campaign_Name: "Fundraisers for people in Pakistan",
    Campaign_Details: [
      {
        Utm_source: "Google",
        Visits: 1,
        Donations: 80,
        Total_Donations: 1,
        Average_Donations: 1,
        Conversion_rate: 0.0000001,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
      {
        Utm_source: "Facebook",
        Visits: 10,
        Donations: 80000,
        Total_Donations: 1520000,
        Average_Donations: 900,
        Conversion_rate: 0.0001,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
      {
        Utm_source: "Twitter",
        Visits: 1110,
        Donations: 80000,
        Total_Donations: 1000,
        Average_Donations: 900,
        Conversion_rate: 0.0001,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
      {
        Utm_source: "Instagram",
        Visits: 1110,
        Donations: 66000,
        Total_Donations: 100,
        Average_Donations: 10000,
        Conversion_rate: 0.0001,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
      {
        Utm_source: "Snapchat",
        Visits: 1110,
        Donations: 66000,
        Total_Donations: 14400,
        Average_Donations: 100,
        Conversion_rate: 0.0001,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
    ],
  },
  {
    _id: "a1b1c1d1",
    Campaign_Name: "Fundraisers for people in palestine and kashmir",
    Campaign_Details: [
      {
        Utm_source: "Google",
        Visits: 1000,
        Donations: 800,
        Total_Donations: 100,
        Average_Donations: 30,
        Conversion_rate: 0.01,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
      {
        Utm_source: "Facebook",
        Visits: 1,
        Donations: 8,
        Total_Donations: 10000,
        Average_Donations: 9,
        Conversion_rate: 0.0001,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
      {
        Utm_source: "Twitter",
        Visits: 1110,
        Donations: 80000,
        Total_Donations: 152,
        Average_Donations: 9,
        Conversion_rate: 0.0001,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
      {
        Utm_source: "Instagram",
        Visits: 1110,
        Donations: 66000,
        Total_Donations: 150,
        Average_Donations: 10,
        Conversion_rate: 0.01,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
      {
        Utm_source: "Snapchat",
        Visits: 1110,
        Donations: 60,
        Total_Donations: 154400,
        Average_Donations: 10000,
        Conversion_rate: 0.0001,
        Utm_medium: "Cps",
        Utm_campaign: "Spring_Sale",
        Utm_term: "Running+shoes",
        Utm_content: "logoglink",
      },
    ],
  },
];
